import { UserProvider } from '@/providers/UserProvider'
import './globals.css'
import { SocketProvider } from '@/providers/SocketProviders'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: 'Chat App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SocketProvider>
        <ToastContainer
              position="top-right"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
            />
          <UserProvider>
            {children}
          </UserProvider>
        </SocketProvider>
      </body>
    </html>
  )
}
